(async () => {
  const passed = [];
  const $ = s => document.querySelector(s);
  const click = s => { const el = $(s); if (!el) throw Error(`Missing control: ${s}`); el.click(); };
  const input = (s, value, event = 'input') => { $(s).value = value; $(s).dispatchEvent(new Event(event, { bubbles: true })); };
  const check = (name, condition) => { if (!condition) throw Error(name); passed.push(name); };
  const submit = s => $(s).requestSubmit();
  const tab = name => click(`#bottom-nav [data-tab="${name}"]`);
  if ($('#skip-welcome')) {
    check('Default entry shows onboarding before the app', !!$('.welcome-page[data-slide="0"]') && $('#bottom-nav').hidden);
    click('#next-welcome');
    check('Welcome advances to the organization screen', !!$('.welcome-page[data-slide="1"]'));
    click('#next-welcome');
    check('Third welcome screen introduces search', !!$('.welcome-page[data-slide="2"]'));
    click('#back-welcome');
    check('Welcome back navigation works', !!$('.welcome-page[data-slide="1"]'));
    click('#next-welcome');
    click('#next-welcome');
    check('Final welcome action leads to setup', !!$('#setup-form'));
    input('#setup-pass', 'verma-demo');
    input('#confirm-pass', 'does-not-match');
    submit('#setup-form');
    check('Setup catches a mismatched confirmation', $('#setup-error').textContent.includes('don’t quite match'));
    input('#confirm-pass', 'verma-demo');
    submit('#setup-form');
    check('Recovery step waits for acknowledgment', $('.recovery-words').children.length === 24 && $('#finish-setup').disabled);
    click('#saved-words');
    click('#finish-setup');
    check('Setup offers the existing vault and import paths', !!$('#content [data-tab="vault"]') && !!$('#content [data-tab="import"]'));
    click('#content [data-tab="vault"]');
    check('Completed onboarding opens the vault', !!$('#vault-search') && !$('#bottom-nav').hidden);
  }
  input('#vault-search', 'github');
  check('Search narrows to GitHub', $('#vault-list').querySelectorAll('.entry-row').length === 1 && $('#vault-list').textContent.includes('GitHub'));
  input('#vault-search', '');
  click('[data-filter="note"]');
  check('Notes filter returns only the note', $('#vault-list').querySelectorAll('.entry-row').length === 1);
  click('#vault-list [data-open]');
  check('Note contents start hidden', $('#secret-value').textContent.includes('••••'));
  click('#reveal-secret');
  check('Explicit reveal shows the note', $('#secret-value').textContent.includes('Verma Home\n'));
  click('#edit-item');
  check('Editing preserves multiline notes', $('#item-secret').tagName === 'TEXTAREA' && $('#item-secret').value.includes('\n'));
  click('[data-action="close"]');
  tab('vault');
  click('#bottom-nav [data-action="add"]');
  input('#item-type', 'note', 'change');
  input('#item-title', '<b>QA note</b>');
  input('#item-secret', 'Sample line one\nSample line two');
  submit('#item-form');
  check('New item is immediately searchable', $('#vault-list').textContent.includes('<b>QA note</b>'));
  check('User content is escaped', !$('#vault-list').querySelector('b'));
  click('#vault-list [data-open]');
  click('#reveal-secret');
  check('New secret value is retained', $('#secret-value').textContent === 'Sample line one\nSample line two');
  click('[data-action="close"]');
  click('#vault-list [data-open]');
  check('Reopening re-hides secrets', $('#secret-value').textContent.includes('••••'));
  const focusable = [...$('#sheet').querySelectorAll('button:not([disabled]), input, select, textarea')];
  focusable.at(-1).focus();
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', bubbles: true, cancelable: true }));
  check('Dialog focus is contained', document.activeElement === focusable[0]);
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  check('Escape dismisses the sheet', $('#sheet').hidden);
  tab('ask');
  input('#ask-query', 'my work google account');
  submit('#ask-form');
  check('Assistant finds the work account', $('#ask-results .entry-row').textContent.includes('Work account'));
  click('#app-header [data-action="privacy"]');
  click('#assistant-toggle');
  click('[data-action="close"]');
  check('Assistant off state is actionable', !$('#ask-form') && $('#content').textContent.includes('Search my vault'));
  tab('import');
  click('#load-import');
  check('Import works with assistant switched off', !!$('#save-import') && $('#save-import').disabled);
  input('#tag-0', 'QA work');
  click('[data-accept="0"]');
  click('[data-duplicate="skip"]');
  check('Duplicate decision enables confirmation', !$('#save-import').disabled && $('#save-import').textContent.includes('6'));
  click('#save-import');
  check('Import has a final confirmation', !!$('#confirm-import'));
  click('#confirm-import');
  check('Import completes with accurate count', $('#content h1').textContent.includes('6 little things'));
  tab('vault');
  input('#vault-search', 'slack');
  check('Edited import tags are retained', $('#vault-list').textContent.includes('QA work'));
  tab('import');
  click('#undo-import');
  tab('vault');
  check('Import undo removes only imported items', $('#vault-list').querySelectorAll('.entry-row').length === 0);
  input('#vault-search', 'QA note');
  check('Undo keeps unrelated added items', $('#vault-list').querySelectorAll('.entry-row').length === 1);
  tab('devices');
  click('#toggle-sync');
  check('Paused sync state appears', $('#content').textContent.includes('Sync paused'));
  click('#pair-device');
  input('#device-name', 'QA laptop');
  click('#pair-confirm');
  check('Pairing adds a demo device', $('#content').textContent.includes('QA laptop'));
  click('#app-header [data-action="lock"]');
  check('Lock hides content and main navigation', $('#bottom-nav').hidden && !$('#content').textContent.includes('QA laptop'));
  input('#unlock-passphrase', 'wrong-demo-value');
  submit('#unlock-form');
  check('Wrong demo phrase is rejected', $('#unlock-error').textContent.includes('doesn’t match'));
  input('#unlock-passphrase', 'verma-demo');
  submit('#unlock-form');
  check('Correct demo phrase unlocks', !$('#bottom-nav').hidden);
  check('No horizontal overflow', document.documentElement.scrollWidth <= innerWidth);
  return JSON.stringify({ passed, total: passed.length });
})()
